import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from 'next/link';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-br from-gray-100 to-blue-50 min-h-screen">
        <nav className="bg-white shadow mb-8">
          <div className="max-w-4xl mx-auto px-4 py-4 flex items-center justify-between">
            <div className="flex items-center gap-6">
              <Link href="/" className="text-xl font-bold text-blue-700 hover:text-blue-900 transition">Admin Home</Link>
              <Link href="/pages-editor" className="text-blue-600 hover:text-blue-800 font-medium transition">Pages Editor</Link>
              <Link href="/pages-content" className="text-blue-600 hover:text-blue-800 font-medium transition">Pages Content</Link>
            </div>
            <span className="text-xs text-gray-400">Simple CMS</span>
          </div>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
